# Generated by Django 5.2.6 on 2025-09-16 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_index=True, max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(db_index=True, max_length=100, verbose_name='Фамилия')),
                ('middle_name', models.CharField(db_index=True, max_length=100, verbose_name='Отчество')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='Описание')),
                ('available', models.BooleanField(default=True, verbose_name='Доступность')),
                ('phone', models.CharField(blank=True, max_length=12, verbose_name='Телефон')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Район')),
                ('available', models.BooleanField(default=True, verbose_name='Доступность')),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Вид спорта')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='Описание')),
                ('available', models.BooleanField(default=True, verbose_name='Доступность')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Место')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='Описание')),
                ('available', models.BooleanField(default=True, verbose_name='Доступность')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.district', verbose_name='Район')),
            ],
        ),
        migrations.CreateModel(
            name='SportPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Цена')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Платно')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.place')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.sport')),
            ],
        ),
        migrations.CreateModel(
            name='CoachSportPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.coach')),
                ('sport_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.sportplace')),
            ],
        ),
    ]
